### ISSUE TITLE
[CLOSED] Adapt Shoot Manifest

### ISSUE THREAD

**Issue by msohn** [msohn/issuemigration#66]
<a href="https://github.wdf.sap.corp/d065849"><img src="https://github.wdf.sap.corp/avatars/u/18025?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [d065849](https://github.wdf.sap.corp/d065849)**
_Friday Aug 04, 2017 at 07:10 GMT_
_Originally opened as https://github.wdf.sap.corp/kubernetes-attic/garden-operator/issues/66_

----

We need to adapt the Shoot object specification to support more cloud providers.

Furthermore, in order to have a more precise status information of a Shoot cluster which can be shown in the Gardener UI, we decided to modify the `.status` part of a Shoot cluster's manifest in the following way:

```
status:
  conditions:
  - lastTransitionTime: 2017-08-01T19:38:38Z
    message: etcd, apiserver, vpn-seed, readvertiser, controller manager and scheduler are running
    reason: AllContainersInRunningState
    status: "True"
    type: ControlPlaneHealthy
  - lastTransitionTime: 2017-08-01T19:38:38Z
    message: Every node registered to the cluster is ready
    reason: EveryNodeReady
    status: "True"
    type: EveryNodeReady
  - lastTransitionTime: 2017-08-01T19:38:38Z
    message: Every container in the kube-system namespace of the Shoot cluster is running
    reason: AllContainersInKubeSystemInRunningState
    status: "True"
    type: SystemComponentsHealthy
  gardenOperatorVersion: "7"
  gardenOperatorName: "gardener-operator-2987160579-w8xgp" # hostname of the operator which is currently working (or which worked as the last) on the Shoot
  lastOperation:
    type: Create # Create|Update|Delete
    state: Succeeded # Processing|Succeeded|Error|Failed
    description: "Hat alles geklappt"
    lastUpdateTime: 2017-08-01T19:38:38Z
    progress: 54 # percentage of how much work has been done (can be shown in the UI)
```
