### ISSUE TITLE
[CLOSED] Operator Refactoring/Split-Up Proposal

### ISSUE THREAD

**Issue by msohn** [msohn/issuemigration#79]
<a href="https://github.wdf.sap.corp/i068969"><img src="https://github.wdf.sap.corp/avatars/u/4644?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [i068969](https://github.wdf.sap.corp/i068969)**
_Thursday Aug 17, 2017 at 14:50 GMT_
_Originally opened as https://github.wdf.sap.corp/kubernetes-attic/garden-operator/issues/79_

----

# Refactoring proposal v2

tl;dr garden-operator is too complex; split it in multiple controllers in Seed clusters that manage `Helm Releases` and `Terraform` Jobs.

## Current issues

In the current state garden-operator is a complex monolith beast. Its architecture won't scale with hundreds / thousands of clusters and many dozens seed clusters. Checking if the cluster is in correct state can involve lots of conditional logic. Putting all the logic in one place can be a short win, but in the long run it will be a lost cause as complexity increases.

Installation of infrastructure / addons / control plane happens via go-lang templates, Helm charts and Terraform jobs with go-lang templates. Cleanup operations for said components can only be achieve by writing more conditional logic in the garden-operator.

### Garden-operator

Garden-operator should act as a federation controller - only do CRUD operations on TPR/CRD(s) in Seed clusters. This will greatly reduce network latency to the API servers and CloudProvider's APIs and the occasional SAP network outages / hiccups. All the logic for CRUD of Shoot clusters is dedicated to Seed clusters.

### New TPR/CRD & Operators

Several TPR/CRD should be created in each Seed and Shoot cluster. All controllers bellow should try to apply the [best practices for writing controllers](https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md):

#### HelmRelease TPR/CRD

`HelmRelease` is a Helm Chart release installed and managed in a cluster (any cluster):

```
apiVersion: garden.k8s.sapcloud.io/v1
kind: HelmRelease
metadata:
  name: control-plane-stack
  namespace: my-shoot-cluster
spec:
  chart:
    path: stable/control-plane-stack | /some-dir/control-plane-stack | https://chart.repo/control-plane-1.2.3.tgz
    version: 1.2.3
    # secret containing the custom values for the chart
    # optional
    valuesSecret: control-plane-stack-secret
status:
  # every status that is defined in
  # https://github.com/kubernetes/helm/blob/4c1a47480e70cabb5d9e227bc55bd75ea9406de0/pkg/proto/hapi/release/status.pb.go#L19-L36
  helmStatus: Unkown | Deployed | Deleted | Suspended | Failed | Deleting | PendingInstall | PendingUpgrade | PendingRollback
  lastWorkingRevision: 4
```

#### HelmReleaseOprator

`HelmReleaseOperator` handles create/update/delete operations on the Tiller server.

Two K8S API resources are monitored for changes (using informers and stores):
- `HelmRelease`
- `Secrets` (any modification of a secret required in a `HelmRelease` must trigger upgrade)

Scenario:

> Note: All scenarios bellow happen in a seed cluster

Create `HelmRelease`:
- `kubectl create -f control-plane-stack.yaml`
- operator sees that a new `HelmRelease` resource is created, finds the chart (mounted via ConfigMap / downloaded from some Helm Repo), finds the secret associated with that release and calls the Tiller server to install the needed chart. It sets the Status in `helmStatus`.

Update `HelmRelease`:
- `kubectl apply -f control-plane-stack-v2.yaml`
- operator sees that an existing `HelmRelease` is modified checks the status of the running `HelmRelease` and does a helm Upgrade (or install if the release is deleted for some reason).

Delete `HelmRelease`:
- `kubectl delete -f control-plane-stack-v2.yaml`
- operator sees that Helm Release wants to be deleted and calls Tiller for deletion with purge.

Additionally there is a `resync` loop that periodically calls Tiller and updates the `helmStatus` of the releases (resources may be deleted / not created) triggering install / upgrade / rollback of a release. This loop may run in different binary or be part of the `HelmReleaseOperator`. It's only job is to update the status of the corresponding HelmRelease. Using this loop we can guarantee that resources are always available for a `HelmRelease`.

#### Terraform TPR/CRD

`Terraform` TPR/CRD handles changes to infrastructure:

```
apiVersion: garden.k8s.sapcloud.io/v1
kind: Terraform
metadata:
  name: worker-infra
  namespace: my-shoot-cluster
spec:
  chart:
    # secrets for the terraform - AWS keys etc. (optional)
    secret: worker-infra-secret
    # Terraform workload
    config: worker-infra-config
status: Applied | Applying | Destroying | NeedsApply | Failed
```

#### TerraformOperator

`TerraformOperator` handles create/update/delete operations based on `Terraform` configuration:

Four K8S API resources are monitored for changes (using informers and stores):
- `Terraform`
- `Job` (and CronJob when it hits [beta in 1.8](https://github.com/kubernetes/kubernetes/issues/41039#issuecomment-320960821))
- `Secret` (any modification of a secret required in a `Terraform` job must trigger `terraform apply`)
- `ConfigMap` (any modification of a configmap required in a `Terraform` job must trigger `terraform apply`)

Scenario:

> Note: All scenarios bellow happen in a seed cluster

Create `Terraform`:
- `kubectl create -f worker-infra.yaml`
- operator sees that a new `Terraform` resource is created. It creates a Job with all the needed configurations and secrets. The Job executes `terraform apply ....`(via `run.sh`). Once the job is finished record the status in `status`.

Update `Terraform`:
- `kubectl apply -f worker-infra.yaml`
- operator sees that a existing `Terraform` resource is updated. It executes the same steps as in Create `Terraform` step

Delete `Terraform`:
- `kubectl delete -f worker-infra.yaml`
- operator sees that a existing `Terraform` resource is deleted. It creates a Job with all the needed configurations and secrets. The Job executes `terraform destroy ....`(via `run.sh`). Once the job is finished record the status in `status`.

Additionally there is a `resync` loop that periodically changes the status of the `Terraform` resource to `NeedsApply`, triggering the operator to perform `terraform apply...`. This can be achieved via CronJob in the 1.8

#### DNSTerraformOperator

This is similar to [ExternalDNS](https://github.com/kubernetes-incubator/external-dns), but we can't use it due to the lack of support for OpenStack(is this a requirement?)

Three K8S API resources are monitored for changes (using informers and stores):
- `Terraform`
- `Service`
- `ConfigMap`

Once a service is annotated with `external-dns.alpha.garden.k8s.sapcloud.io`
```
kubectl expose deployment kube-apiserver --port=443 --target-port=443 --type=LoadBalancer
kubectl annotate service kube-apiserver "external-dns.alpha.garden.k8s.sapcloud.io/hostname=api.my-cluster.k8s.sapcloud.io."
```

The operator creates a `Terraform` resource with the ELB's endpoint as a configuration. The `Terraform` job automatically creates the needed `Route53` resource and starts to reconcile.

### Operators cont

All operators can be bundled together in a single binary (like k8s's `controller-manager`) or deployed independently from one another.

## Cluster Create Scenario

* A new cluster is created in the Garden-UI
* Shoot resource is created
* Garden-Operator selects a Seed Cluster and creates all needed secrets, HelmRelease....
* as a prerequisite in Seed both `Tiller` and previous mentioned operators are deployed
* Multiple `HelmRelease`s with control plane components, monitoring stack, [addon-manager](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager)...  are deployed
  > Note: addon-manager will connect to its own k8s Shoot api server
* In the control plane `HelmRelease` there is a nested `Terraform` that creates the infra for the shoot cluster.
  > Note this nested `Terraform` will play a role in the Cluster deletion operation later on.
* Shoot's API server is annotated with `external-dns.alpha.garden.k8s.sapcloud.io/hostname=api.my-cluster.k8s.sapcloud.io.`
* in addon-manager's mounted ConfigMaps are all managed by us resources that needs to be created and Reconciled in the Shoot cluster, including:
  * Tiller
  * mentioned before operators
  * `HelmReleases` with different operators and optional `Terraform` resources

### Prerequisites

The delete cluster scenario is special because we need to do several things, before we tear down the infra we create for workers:

* both `Tiller` and previous mentioned operators needs to be deployed
* Stop `addon-manager`
* Delete all `HelmReleases` in the Shoot cluster - helm charts can have `pre-delete` and `post-delete` hooks to clean up resources created in some third-party systems (think accounts in SuccessFactors, Ariba...., credentials ....)
* Delete all `Terraform` resources to clean up CloudProvider resources created by addons in the shoot cluster
  > Note: previous 2 steps can be a `post-delete` step in the deletion of `addon-manager`

### Scenario:

* An exising cluster is deleted in the Garden-UI
* Shoot resource is scheduled for deletion
* See Prerequisites
* Delete the Shoot Cluster namespace, triggering deletion of all `HelmReleases` and `Terraform`

## Cluster Update Scenario

The only tricky part for the Upgrade scenario is `kubelet` upgrades. In our current setup this can only be achieved by modifying the launch configuration for nodes. The rest of the components can be upgraded by simply modifying all `HelmReleases`, `ConfigMaps`, `Secrets` and `Terraform`.

This will also allow us to do a rolling upgrade of Shoot-clusters from the garden operator.

Edits:
[0] Fixed typos
